name: Deploy

on:
  push:
    branches:
      - docs-deploy

jobs:
  github-branch-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm docs:build

      - name: Update the gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: docs/.vitepress/dist

  # search-algolia:
  #   needs: [github-branch-update]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out the repository
  #       uses: actions/checkout@v3

  #     - name: Push indices to Algolia
  #       uses: peiyanlu/algolia-docsearch-action@master
  #       with:
  #         algolia_application_id: ${{ secrets.ALGOLIA_APP_ID }}
  #         algolia_api_key: ${{ secrets.ALGOLIA_API_KEY }}
  #         algolia_config_file: algolia.config.json
